language: python
addons:
  apt:
    packages:
      - graphviz
install: pip3 install --upgrade pip && pip3 install .[test,CI]
script:
  - pytest --cov-report=xml --cov=algograph
python:
  - "3.7"
after_success:
  - codecov


language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python on Linux"
    - name: "Python on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version=3.7.5
        - python -m pip install --upgrade pip
        # - choco install graphviz
        - wget https://graphviz.gitlab.io/_pages/Download/windows/graphviz-2.38.msi
        - msiexec /i "graphviz-2.38.msi" /quiet
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
